myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.models import Group

admin.site.unregister(Group)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('about/', views.about),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls')),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/posts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'posts'
urlpatterns = [
    path('', views.Postes_Listes, name='listes'),
    path('stages_list', views.Stages_list, name='stages_list'),
    path('stage-edit/<int:id>/', views.edit_stage, name='stage-edit'),
    path('evencluv-edit/<int:id>/', views.evenClub_update_view, name='evenclubupdate'),
    path('stage-delete/<int:pk>/', views.StageDeleteView.as_view(), name='stage-delete'),
    path('evenclub-delete/<int:pk>/', views.EvenClubDeleteView.as_view(), name='evenclub-delete'),
    path('ajouter/', views.CreerStage.as_view(), name='creer_stage'),
    path('ajouterEvenClub/', views.creerEvenClub.as_view(), name='creer_EvenClub'),
    path('like-post', views.like_post, name='like-post'),
    path('even_club_list', views.EvenClub_list, name="evenclublist"),
   path('new-post/', views.post_new, name='new-post'),
    path('<slug:slug>', views.Poste_page, name='poste_page'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/users/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'users'

urlpatterns = [ 
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('password-reset/', views.ResetPasswordView.as_view(), name='password_reset'),
     path('profile/', views.profile, name='users-profile'),
      path('password-change/', views.ChangePasswordView.as_view(), name='password_change'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/templates/about.html
{% extends "layout.html" %} 

{%block title%}
about
{% endblock %}


{% block content %}
<link rel="stylesheet" href="/static/css/about.css">

    <header>
        <h1>Application Web « Student Help »</h1>
        <p>Au profit des étudiants de l'université</p>
    </header>
    <main>
        <section>
            <h2>Description Fonctionnelle</h2>
            <p>L’application offrira les offres et/ou demandes des services suivants :</p>
            <ul>
                <li><strong>Logement</strong> proche de la faculté pour minimiser le coût et le temps du transport.</li>
                <li><strong>Transport</strong> en commun ou de co-voiturage.</li>
                <li>
                    <strong>Sujets de stages</strong> présentés par les partenaires ou demandés par les étudiants selon leurs niveaux d’études.
                    <ul>
                        <li>Possibilité d'ajouter des affectations des encadreurs.</li>
                    </ul>
                </li>
                <li>
                    <strong>Évènements culturels ou scientifiques</strong> organisés au profit des étudiants.
                    <ul>
                        <li>
                            Évènements <em>culturels</em> (pièce de théâtre, film, présentation musicale) avec spécification du prix.
                        </li>
                        <li>
                            Évènements <em>scientifiques</em> organisés par un club particulier de l’université avec spécification du domaine ou sujet.
                        </li>
                    </ul>
                </li>
                <li><strong>Recommandation</strong> : idée ou recommandation que l’utilisateur pourra partager avec sa communauté.</li>
            </ul>
        </section>

        <section>
            <h2>Accessibilité</h2>
            <p>Le site peut être accessible aux étudiants de l’université, enseignants ou toute autre personne externe après inscription.</p>
            <p>Dès sa connexion, l’utilisateur pourra consulter toutes les publications (posts) ou déposer une nouvelle offre et éventuellement supprimer l’une de ses posts.</p>
        </section>

        <section>
            <h2>Fonctionnalités Avancées</h2>
            <ul>
                <li>Les publications (Stage, Logement, Évènement, Transport) peuvent être commentées et/ou adorées par les utilisateurs.</li>
                <li>Pour chaque commentaire ou mention "j’aime", une notification est envoyée à celui qui a déposé la publication.</li>
                <li>
                    Recherche par mot clé pour chaque service :
                    <ul>
                        <li>Adresse pour un logement.</li>
                        <li>Destination pour le transport.</li>
                        <li>Type pour un stage.</li>
                        <li>Nom du club pour un évènement.</li>
                    </ul>
                </li>
                <li>Formulaire d’inscription/réservation à l’évènement, transport, logement ou stage.</li>
                <li>
                    Traitement automatique pour supprimer les publications passées :
                    <ul>
                        <li>Stage affecté.</li>
                        <li>Transport passé.</li>
                        <li>Évènements passés.</li>
                        <li>Logement réservé ou tous les postes passés depuis un mois.</li>
                    </ul>
                    <p>Le système pourra demander l’avis de l’annonceur pour supprimer ou prolonger la durée de l'annonce.</p>
                </li>
            </ul>
        </section>

        <section>
            <h2>Extensions et Améliorations</h2>
            <p>Toute autre extension ou amélioration sera appréciée.</p>
        </section>
    </main>
    <footer>
        <p>&copy; 2024 Université - Application Student Help</p>
    </footer>



{% endblock %}

myproject/templates/home.html
 {% extends "layout.html" %} 

 {%block title %}
 home
 {% endblock %}

 {% block content %}

 <h1>Home</h1>
 <p>check out my <a href="/about">about</a> page.</p>
 
 {% endblock %}

myproject/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Django App
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/main.js' %}" defer></script>
</head>
<body>
    <nav>
        <a href="/">
            <span role="img" aria-label="Home" title="Home">🏠</span>
        </a> | 
        <a href="/about">
            <span role="img" aria-label="About" title="About">😀</span>
        </a> | 
        <a href="{% url 'posts:listes' %}">
            <span role="img" aria-label="Posts" title="Posts">📰</span>
        </a> | 
        {% if user.is_authenticated %}
            <a href="{% url 'posts:new-post' %}">
                <span role="img" aria-label="New Post" title="New Post">🆕</span>
            </a> | 
            <form class="logout" action="{% url 'users:logout' %}" method="post">
                {% csrf_token %} 
                <button class="logout-button" aria-label="User Logout" title="User Logout">👋</button>
            </form>
            <a href="{% url 'users:users-profile' %}">
                <span role="img" aria-label="User profile" title="User Profile">Profile</span>
            </a>
            <div class="dropdown">
                <button class="dropbtn">Posts</button>
                <div class="dropdown-content">
                  <a href="{% url 'posts:stages_list' %}">Stage</a>
                  <a href="">Logement</a>
                  <a href="#">Evenement</a>
                  <a href="#">EvenSocial</a>
                  <a href="{% url  'posts:evenclublist' %}">EvenClub</a>
                </div>
              </div>
              <div class="dropdown">
                <button class="dropbtn">Create Post</button>
                <div class="dropdown-content">
                  <a href="{% url 'posts:creer_stage' %}">Stage</a>
                  <a href="#">Logement</a>
                  <a href="#">Evenement</a>
                  <a href="#">EvenSocial</a>
                  <a href="{% url 'posts:creer_EvenClub' %}">EvenClub</a>
                 
                </div>
                <form class="logout" action="{% url 'users:logout' %}" method="post">
                    {% csrf_token %} 
                    <button class="logout-button" aria-label="User Logout" title="User Logout"> Hello: {{user.username}} </button>
                </form>

              </div>
        {% else %}
            <a href="{% url 'users:register' %}">
                <span role="img" aria-label="User Registration" title="User Registration">🚀</span>
            </a> | 
            <a href="{% url 'users:login' %}">
                <span role="img" aria-label="User Login" title="User Login">🔏</span>
            </a>
           

        {% endif %}
    </nav>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>