myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.models import Group

admin.site.unregister(Group)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('about/', views.about),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls')),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/posts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'posts'
urlpatterns = [
    path('', views.Postes_Listes, name='listes'),
    path('stages_list', views.Stages_list, name='stages_list'),
    path('stage-edit/<int:id>/', views.edit_stage, name='stage-edit'),
    path('evencluv-edit/<int:id>/', views.evenClub_update_view, name='evenclubupdate'),
    path('stage-delete/<int:pk>/', views.StageDeleteView.as_view(), name='stage-delete'),
    path('evenclub-delete/<int:pk>/', views.EvenClubDeleteView.as_view(), name='evenclub-delete'),
    path('ajouter/', views.CreerStage.as_view(), name='creer_stage'),
    path('ajouterEvenClub/', views.creerEvenClub.as_view(), name='creer_EvenClub'),
    path('like-post', views.like_post, name='like-post'),
    path('even_club_list', views.EvenClub_list, name="evenclublist"),
   path('new-post/', views.post_new, name='new-post'),
    path('<slug:slug>', views.Poste_page, name='poste_page'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.



class Poste(models.Model):
    image = models.ImageField( blank=True)
    # 'type' is a reserved keyword, let's use another name like 'post_type'
    # You can use choices to specify the options for the type field
    POST_TYPE_CHOICES = (
        (0, 'Offre'),
        (1, 'Demande'),
    )
    post_type = models.IntegerField(choices=POST_TYPE_CHOICES)
    date = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE,default=None)
    no_of_likes = models.IntegerField(default=0)

class Recommandation(Poste):  # Inheriting from Poste
    recom = models.TextField() 
    
class LikePost(models.Model):
    post_id = models.CharField(max_length=500)
    username = models.CharField(max_length=100)

    def __str__(self):
        return self.username

# class Transport(Poste):
#     depart = models.TextField()
#     destination = models.TextField()
#     heureDep = models.DateTimeField()
    
class Logement(Poste):
    localisation = models.TextField()
    description = models.TextField()
    contactInfo = models.TextField()

class Stage(Poste):
    STAGE_TYPE_CHOICES = (
        (0, 'ouvrier'),
        (1, 'technicien'),
        (1, 'PFE'),
    )
    typeStage = models.IntegerField(choices=STAGE_TYPE_CHOICES)
    societe = models.TextField()
    duree = models.IntegerField()
    sujet = models.TextField()
    contactInfo = models.TextField()
    specialité = models.TextField()

class Evenement(Poste):
    intitulé = models.TextField()
    description = models.TextField()  
    lieu = models.TextField()
    contactInfo = models.TextField()
    
class EvenSocial(Evenement):
    prix = models.FloatField((""))

class EvenClub(Evenement):
    club = models.TextField()
    

myproject/posts/forms.py
from django import forms 
from . import models 



        
class StageForm(forms.ModelForm):
    class Meta:
        model = models.Stage
        fields = ['image', 'post_type', 'date', 'author','typeStage', 'duree'  , 'societe', 'sujet', 'contactInfo', 'specialité'  ]  # List only the fields you want to display

class CreateLogment(forms.ModelForm):
    class Meta:
        model = models.Logement
        fields = '__all__'
        
class CreateEvenClub(forms.ModelForm):
    class Meta:
        model = models.EvenClub
        fields = ['image', 'post_type', 'author','intitulé', 'description', 'lieu', 'contactInfo', 'club'  ]  # List only the fields you want to display

myproject/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import  Poste, Stage, Logement, LikePost, EvenClub
from users.models import Profile
from django.conf import settings
from django.contrib.auth.decorators import login_required
from . import forms
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django. contrib import messages
from django.views.generic.edit import  DeleteView, CreateView
from django.urls import reverse_lazy
from .forms import StageForm
from django.http import JsonResponse, HttpResponseRedirect
from django.views.decorators.http import require_GET
from django.contrib.auth.models import User, auth
from django.utils.decorators import method_decorator





# Create your views here.

def Postes_Listes(request):
    stages = Stage.objects.all()
    logements = Logement.objects.all()
    evenclub = EvenClub.objects.all()
    return render(request, 'posts/postes_list.html', {'stages': stages, 'logements': logements, 'evenclub': evenclub})

def Stages_list(request):
    stages = Stage.objects.all()
    return render(request, 'posts/Stages_list.html', { 'stages': stages })    

def EvenClub_list(request):
    evenClub = EvenClub.objects.all()
    return render(request, 'posts/even_club_list.html', {'evenClub': evenClub})

def Poste_page(request, slug):
    post = Poste.objects.get(slug=slug)
    return render(request, 'posts/post_page.html', {'post' : post} )

@login_required
def edit_stage(request, id):
    stage = get_object_or_404(Stage, id=id)
    if request.method == 'GET':
        context = {'form': forms.StageForm(instance=stage), 'id' : id}
        return render(request,'posts/stage_EditForm.html',context)
    elif request.method == 'POST':
        form = forms.StageForm(request.POST, instance=stage)
        if form.is_valid():
            form.save()
            messages.success(request, 'The post has been updated successfully.')
            return redirect("stages_list")
    else:
            messages.error(request, 'Please correct the following errors:')
            return render(request,'posts/stage_EditForm.html',{'form':form})

@method_decorator(login_required, name='dispatch')
def evenClub_update_view(request, id):
    evenclub = get_object_or_404(EvenClub, id=id)
    
    if request.method == "GET":
        form = forms.CreateEvenClub(instance=evenclub)
        context = {'form': form, 'id': id}
        return render(request, 'posts/even_club_update_view.html', context)
    
    elif request.method == 'POST':
        form =forms. CreateEvenClub(request.POST, instance=evenclub)
        if form.is_valid():
            form.save()
            messages.success(request, 'The post has been updated successfully.')
            return redirect("posts:listes")
        else:
            messages.error(request, 'Please correct the following errors:')
    
    context = {'form': form, 'id': id}
    return render(request, 'posts/even_club_update_view.html', context)

    
@method_decorator(login_required, name='dispatch')
class StageDeleteView(DeleteView):
    model = Stage
    template_name = 'posts\stage_delete.html'
    success_url = reverse_lazy('posts:listes')
@method_decorator(login_required, name='dispatch')
class EvenClubDeleteView(DeleteView):
    model = EvenClub
    template_name = 'posts\evenclub_delete.html'
    success_url = reverse_lazy('posts:listes')


    
@method_decorator(login_required, name='dispatch')
class CreerStage(CreateView):
   model = Stage
   template_name = 'posts/stage_form.html'
   form_class = StageForm   
   success_url = reverse_lazy('posts:listes')
   
   
   
   
   
@method_decorator(login_required, name='dispatch')
class creerEvenClub(CreateView):
    model = EvenClub
    template_name = 'posts/evenClubForm.html'
    form_class = forms.CreateEvenClub
    success_url = reverse_lazy('posts:listes')




    

@login_required(login_url="/users/login/")
def post_new(request):
    if request.method == 'POST':
        form = forms.CreatePost(request.POST, request.FILES)
        if form.is_valid():
            newpost = form.save(commit=False)
            newpost.author = request.user
            newpost.save()
            return redirect('posts:listes')
    else:
        form = forms.CreatePost()
    return render(request, 'posts/post_new.html', { 'form ' : form })

@login_required
def profile(request):
    return render(request, 'users/profile.html')


@require_GET
@login_required
def like_post(request):
    username = request.user.username
    post_id = request.GET.get('post_id')
    
    post = Poste.objects.get(id=post_id)
    
    like_filter = LikePost.objects.filter(post_id=post_id, username=username).first()
    
    if like_filter is None:
        new_like = LikePost.objects.create(post_id=post_id, username=username)
        new_like.save()
        post.no_of_likes += 1
        liked = True
    else:
        like_filter.delete()
        post.no_of_likes -= 1
        liked = False
    
    post.save()
    
    return JsonResponse({'no_of_likes': post.no_of_likes, 'liked': liked})


# def search(request):
#     user_Object = User.Objects.get(username=request.user.username)
#     user_profile = Profile.objects.get(user=user_object)
    
#     user_following_list = []
#     feed = []
    
#     user_following = FollowersCount.objects.filter(follower=request.user.username)

myproject/posts/templates/posts/Stages_list.html
{% extends "layout.html" %} 

{% block title %}
    Stages list
{% endblock %}

{% block content %}
<link rel="stylesheet" href="/static/css/post_list.css">
<div class="container">
{% for stage in stages %}
<div class="post-container">
    <div class="post-heade">
        
        <img src="{{ user.profile.avatar.url }}" alt="Photo de profil"> 
        <div class="dropdown">
            <button class="dropbtn">...</button>
            <div class="dropdown-content">
                <a href="{% url 'posts:stage-delete' stage.pk %}">Suprimer</a>
              <a href="{% url 'posts:stage-edit' id=stage.id %}">modifier</a>            </div>
          </div>
        <div class="author-name">{{ stage.author }}</div>
        <p>Typde de Stage: {{ stage.post_type_display }}</p>
        <p>{{ stage.date }}</p>
        <h2>Typde de Stage:{{ stage.get_typeStage_display }}</h2>
        <p>Typde de Poste: {{ stage.get_post_type_display }}</p>
    </div>
    {% if stage.image %}
    <img class="post-image" src="{{ stage.image.url }}" alt="{{ stage.post_type }}" />
{% else %}
    <p></p>
{% endif %}  
    <div class="post-content">
        <p>Societe: {{ stage.societe }}</p>
        <p>Duree: {{ stage.duree }}</p>
        <p>Sujet: {{ stage.sujet }}</p>
        <p>Contact Info: {{ stage.contactInfo }}</p>
        <p>Specialité : {{ stage.specialité }}</p>
    </div>
    <div class="post-actions">

        <div class="flex space-x-4 lg:font-bold">
            <a href="{% url 'posts:like-post' %}?post_id={{ stage.id }}" class="flex items-center space-x-2">
                <div class="p-2 rounded-full text-black">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" width="25" height="25" class="">
                        <path d="M2 10.5a1.5 1.5 0 113 0v6a1.5 1.5 0 01-3 0v-6zM6 10.333v5.43a2 2 0 001.106 1.79l.05.025A4 4 0 008.943 18h5.416a2 2 0 001.962-1.608l1.2-6A2 2 0 0015.56 8H12V4a2 2 0 00-2-2 1 1 0 00-1 1v.667a4 4 0 01-.8 2.4L6.8 7.933a4 4 0 00-.8 2.4z" />
                    </svg>
                </div>
                <div>
                    {% if post.no_of_likes == 0 %}
                        <p>No likes</p>
                    {% elif post.no_of_likes == 1 %}
                        <p>Liked by {{ stage.no_of_likes }} person</p>
                    {% else %}
                        <p>Liked by {{ stage.no_of_likes }} people</p>
                    {% endif %}
                </div>
            </a>
        </div>
        


        <button>Commenter</button>
    </div>
</div>
{% endfor %}
{% for club in evenClub %}
    <div class="card">

        <div class="card-header">
            <img src="{{ club.image.url }}" alt="{{ club.intitulé }}">
        </div>
        <div class="card-body">
            <a href="{% url 'posts:evenclubupdate' id=club.id %}">modifier</a>  
            <a href="{% url 'posts:evenclub-delete' club.pk %}">Suprimer</a>
        </div>

            <span class="tag tag-teal">{{ club.club }}</span>
            <span class="tag tag-teal">{{ club.get_post_type_display }}</span>
            <h4>{{ club.intitulé }}</h4>
            <p>{{ club.description }}</p>
            <p>{{ club.lieu }}</p>
            <p>{{ club.contactInfo }}</p>
            <div class="user">
                <img src="{{ user.profile.avatar.url }}" alt="User profile picture">
                <div class="user-info">
                    <h5>{{ user.username }}</h5>
                    <small>{{ club.date }}</small>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
   
{% endblock %}

myproject/posts/templates/posts/evenClubForm.html
{% extends "layout.html" %}

{% load static %}
{% block title %} Event Club {% endblock title %}
{% block styles %} 
  
    {% endblock %}
    
{% block content %}
<link rel="stylesheet" href="/static/css/post_form.css">

<div class="container">
    <h1>Create a New Event Club stage </h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</div>
{% endblock %}

myproject/posts/templates/posts/even_club_list.html
{% extends 'layout.html' %}

{% block title %}
    Club Event List
{% endblock %}

{% block content %}
<link rel="stylesheet" href="/static/css/even_club_list.css">

<div class="container">
    {% for club in evenClub %}
    <div class="card">

        <div class="card-header">
            <img src="{{ club.image.url }}" alt="{{ club.intitulé }}">
        </div>
        <div class="card-body">
            <a href="{% url 'posts:evenclubupdate' id=club.id %}">modifier</a>  
            <a href="{% url 'posts:evenclub-delete' club.pk %}">Suprimer</a>
        </div>

            <span class="tag tag-teal">{{ club.club }}</span>
            <span class="tag tag-teal">{{ club.get_post_type_display }}</span>
            <h4>{{ club.intitulé }}</h4>
            <p>description: {{ club.description }}</p>
            <p>{{ club.lieu }}</p>
            <p>{{ club.contactInfo }}</p>
            <div class="user">
                <img src="{{ user.profile.avatar.url }}" alt="User profile picture">
                <div class="user-info">
                    <h5>{{ user.username }}</h5>
                    <small>{{ club.date }}</small>
                </div>
                
            </div>
            
        </div>
        
    </div>
    {% endfor %}
</div>

{% endblock %}

myproject/posts/templates/posts/even_club_update_view.html
{% extends "layout.html" %} 
	
{% block content %}
<link rel="stylesheet" href="/static/css/edit_stage_form.css">

<h2>{% if id %} Edit {% else %} New {% endif %} evenClub   </h2>
<form method="post" novalidate>
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Save" />
</form>

{% endblock content %}

myproject/posts/templates/posts/evenclub_delete.html
<!-- stage_delete.html -->

{% extends 'layout.html' %}

{% block content %}
  <div class="container">
    <h2>Delete evenClub</h2>
    <p>Are you sure you want to delete this evenClub?</p>
    <form method="post">
      {% csrf_token %}
      <input type="submit" class="btn btn-danger" value="Delete">
      <a href="{% url 'posts:listes' %}" class="btn btn-secondary">Cancel</a>
    </form>
  </div>
{% endblock %}

myproject/posts/templates/posts/post_page.html
{% extends "layout.html" %} 

{%block title%}
{{ post.title }}
{% endblock %}

{% block content %}
    <section>   
    <h1>{{ post.post_type }}</h1>
            <img   
            class="banner"
            src="{{ post.banner.url }}" 
            alt="{{post.post_type}}"
            />
            <p>{{ post.date }}</p>
</section>
{% endblock %}

myproject/posts/templates/posts/postes_list.html
{% extends "layout.html" %} 

{% block title %}
    Postes list
{% endblock %}

{% block content %}
<link rel="stylesheet" href="/static/css/post_list.css">

<div class="container">
{% for stage in stages %}
<div class="post-container">
    <div class="post-heade">
        <img src="{{ user.profile.avatar.url }}" alt="Photo de profil">
        <div class="author-name">{{ stage.author }}</div>
        <p>{{ stage.date }}</p>
        <p>{{ stage.get_post_type_display }}</p>
    </div>
    {% if stage.image %}
    <img class="post-image" src="{{ stage.image.url }}" alt="{{ stage.post_type }}" />
{% else %}
    <p></p>
{% endif %}  
  <div class="post-content">
        <p>{{ stage.societe }}</p>
        <p>{{ stage.duree }}</p>
        <p>{{ stage.sujet }}</p>
        <p>{{ stage.contactInfo }}</p>
        <p>{{ stage.specialité }}</p>
    </div>
    <div class="post-actions">
        <div class="flex space-x-4 lg:font-bold">
            <a href="{% url 'posts:like-post' %}?post_id={{ stage.id }}" class="flex items-center space-x-2">
                <div class="p-2 rounded-full text-black">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" width="25" height="25" class="">
                        <path d="M2 10.5a1.5 1.5 0 113 0v6a1.5 1.5 0 01-3 0v-6zM6 10.333v5.43a2 2 0 001.106 1.79l.05.025A4 4 0 008.943 18h5.416a2 2 0 001.962-1.608l1.2-6A2 2 0 0015.56 8H12V4a2 2 0 00-2-2 1 1 0 00-1 1v.667a4 4 0 01-.8 2.4L6.8 7.933a4 4 0 00-.8 2.4z" />
                    </svg>
                </div>
                <div>
                    {% if post.no_of_likes == 0 %}
                        <p>No likes</p>
                    {% elif post.no_of_likes == 1 %}
                        <p>Liked by {{ stage.no_of_likes }} person</p>
                    {% else %}
                        <p>Liked by {{ stage.no_of_likes }} people</p>
                    {% endif %}
                </div>
            </a>
        </div>
        <button>Commenter</button>
    </div>
</div>
{% endfor %}

{% for logement in logements %}
<div class="post-container">
    <div class="post-header">
        
        <img src="{{ user.profile.avatar.url }}" alt="Photo de profil">
        <div class="author-name">{{ logement.author }}</div>
        <p>{{ logement.date }}</p>
        <p>{{ stage.get_post_type_display }}</p>
    </div>
    {% if logement.image.url %}
    <img class="post-image" src="{{ logement.image.url }}" alt="{{ logement.post_type }}" />
{% else %}
    <p></p>
{% endif %}

    <div class="post-content">
        <p>{{ logement.localisation }}</p>
        <p>{{ logement.description }}</p>
        <p>{{ logement.contactInfo }}</p>
    </div>
    <div class="post-actions">
        <div class="flex space-x-4 lg:font-bold">
            <a href="{% url 'posts:like-post' %}?post_id={{ logement.id }}" class="flex items-center space-x-2">
                <div class="p-2 rounded-full text-black">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" width="25" height="25" class="">
                        <path d="M2 10.5a1.5 1.5 0 113 0v6a1.5 1.5 0 01-3 0v-6zM6 10.333v5.43a2 2 0 001.106 1.79l.05.025A4 4 0 008.943 18h5.416a2 2 0 001.962-1.608l1.2-6A2 2 0 0015.56 8H12V4a2 2 0 00-2-2 1 1 0 00-1 1v.667a4 4 0 01-.8 2.4L6.8 7.933a4 4 0 00-.8 2.4z" />
                    </svg>
                </div>
                <div>
                    {% if post.no_of_likes == 0 %}
                        <p>No likes</p>
                    {% elif post.no_of_likes == 1 %}
                        <p>Liked by {{ logement.no_of_likes }} person</p>
                    {% else %}
                        <p>Liked by {{ logement.no_of_likes }} people</p>
                    {% endif %}
                </div>
            </a>
        </div>
        <button>Commenter</button>
    </div>
</div>
{% endfor %}
 
</div>
   
{% endblock %}

myproject/posts/templates/posts/stage_EditForm.html
{% extends "layout.html" %} 
	
{% block content %}
<link rel="stylesheet" href="/static/css/edit_stage_form.css">

<h2>{% if id %} Edit {% else %} New {% endif %} Stage   </h2>
<form method="post" novalidate>
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Save" />
</form>

{% endblock content %}

myproject/posts/templates/posts/stage_delete.html
<!-- stage_delete.html -->

{% extends 'layout.html' %}

{% block content %}
  <div class="container">
    <h2>Delete Stage</h2>
    <p>Are you sure you want to delete this stage?</p>
    <form method="post">
      {% csrf_token %}
      <input type="submit" class="btn btn-danger" value="Delete">
      <a href="{% url 'posts:listes' %}" class="btn btn-secondary">Cancel</a>
    </form>
  </div>
{% endblock %}

myproject/posts/templates/posts/stage_form.html
{% extends "layout.html" %}

{% load static %}
{% block title %} Stage {% endblock %}



{% block content %}
<link rel="stylesheet" href="/static/css/post_form.css">

<div class="container">
    <h1>Create a New Post stage</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</div>
{% endblock %}